import { ThreadEventSchema } from "@/app/schemas/realtime";
import { orpc } from "@/lib/orpc";
import { useQueryClient } from "@tanstack/react-query";
import usePartySocket from "partysocket/react";
import { createContext, ReactNode } from "react";

interface ThreadRealtimeProviderProps {
  children: ReactNode;
  threadId: string;
}

const ThreadRealtimeContext = createContext(null);

export function ThreadRealtimeProvider({
  children,
  threadId,
}: ThreadRealtimeProviderProps) {
  const queryClient = useQueryClient();

  type ThreadListOptions = ReturnType<
    typeof orpc.message.thread.list.queryOptions
  >;

  type ThreadQueryData = Awaited<ReturnType<ThreadListOptions["queryFn"]>>;

  const socket = usePartySocket({
    host: "http://127.0.0.1:8787",
    room: `thread-${threadId}`,
    party: "chat",
    onMessage(e) {
      try {
        const parsed = JSON.parse(e.data);

        const result = ThreadEventSchema.safeParse(parsed);
        if (!result.success) {
          console.log("Invalid Thread Event");
          return;
        }

        const event = result.data;

        if (event.type === "thread:reply:created") {
          // Use the same key generated by orpc
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old;

              const reply = {} as ThreadQueryData["messages"][number];
            }
          );
        }
      } catch (error) {}
    },
  });
}
